name: Deploy ASP.NET Core API to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./PdfToWordConverterApi/PdfToWordConverterApi

      - name: Build the API
        run: dotnet build ./PdfToWordConverterApi/PdfToWordConverterApi --configuration Release

      - name: Run tests
        run: dotnet test ./PdfToWordConverterApi/PdfToWordconverterApi.Tests

      - name: Publish the API
        run: dotnet publish ./PdfToWordConverterApi/PdfToWordConverterApi --configuration Release --output ./published-api

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pdftowordapi' # Replace with your Azure Web App name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PDFTOWORDAPI_WEBAPP_PUBLISH_PROFILE }}
          package: ./published-api
